services:
  auth:
    build: .
    image: auth:latest
    container_name: auth_container
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
      - pg-admin
    networks:
      - postgres
      - redis
  redis:
    image: redis:latest
    container_name: redis_container
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
      - ./users.acl:/usr/local/etc/redis/users.acl
    command: >
      sh -c '
      redis-server --include /usr/local/etc/redis/redis.conf --aclfile 
      /usr/local/etc/redis/users.acl '
    networks:
      - redis
  db:
    image: postgres:17-alpine
    container_name: pg_container
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME_PROD}"
      POSTGRES_USER: "${DB_USER_PROD}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD_PROD}"
      PGDATA: "/var/lib/postgresql/data/authpgdata"
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdatamarket
    ports:
      - "5432:5432"
    networks:
      - postgres
  pg-admin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "sample@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5051:80"
    networks:
      - postgres
networks:
  redis:
    driver: bridge
  postgres:
    driver: bridge
volumes:
  pg-data:
  redis-data: